FROM oraclelinux:7-slim
ADD openjdk-10_linux-x64_bin.tar.gz /opt/jdk
ENV PATH=$PATH:/opt/jdk/jdk-10/bin

RUN ["java", "-Xshare:dump"]
ADD HelloContainerDays.class /
CMD ["java", "-Xshare:on", "-showversion", "HelloContainerDays", "From Container"]
